# We're using the latest version of Prefect with Python 3.10
FROM prefecthq/prefect:2-python3.11

# Add our requirements.txt file to the image and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt --trusted-host pypi.python.org --no-cache-dir

# Add our flow code to the image
COPY flow.py /opt/prefect/flows/flow.py

# Run our flow script when the container starts
CMD ["python", "flows/flow.py"]

# extra_pip_packages
# docker option